version = 0.1

[default.deploy.parameters]
stack_name = "abnormal-sensor-data"
resolve_s3 = true
s3_prefix = "abnormal-sensor-data"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "IngestStreamTopicArn=\"arn:aws:sns:us-east-1:272465253817:sensors-data-ingest\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
